#!/bin/bash

CURRENT_PATH="$(pwd)"
NVIM_CONFIG_PATH="$HOME/projects/config/neovim-config/versions"
NVIM_VERSIONS="$(ls "$NVIM_CONFIG_PATH")"

NEW_NVIM="$(gum choose "$NVIM_VERSIONS")"
echo "Using $NEW_NVIM as nvim config" | lolcat

rm -rf ~/.config/nvim
ln -s "$NVIM_CONFIG_PATH/$NEW_NVIM" ~/.config/nvim
