#!/bin/bash

echo "Installing base packages..." | lolcat
yay -S --needed --noconfirm \
	grim slurp aur-talk-git aurpublish yup aurvote-utils \
	package-query util-say-git pipewire bluez brightnessctl \
	chsh zsh

echo "Installing term tools..." | lolcat
yay -S --needed --noconfirm kitty neovim neofetch ranger ripgrep tmux wthrr \
	starship jq autojump fzf fzf-kill kube-fzf zsh-fzf-plugin npm-fzf \
	find-the-command pop noto-fonts-emoji fish

"Installing languages and devtools..." | lolcat
yay -S --needed --noconfirm python3 rustup golang lazygit insomnia jdk-openjdk code-minimap nvm

echo "Installing internet and messaging packages..." | lolcat
yay -S --needed --noconfirm firefox bitwarden bitwarden-cli discord openvpn

echo "Installing security tools" | lolcat
yay -S --needed --noconfirm yubikey-personalization yubico-authenticator-bin yubikey-manager yubico-pam yubico-authenticator-bin pam-u2f
echo "Installing gaming and media packages..." | lolcat

yay -S --needed --noconfirm steam steam-tui lutris cava musickube ytfzf
